name: Create Pull Request

on:
  push:
    branches:
      - main

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2.4.2

    - name: Set remote URL
      run: git remote add original https://github.com/ArthurBrouwersSemester3/Front-end.git

    - name: Fetch branch
      run: git fetch upstream Development

    - name: Checkout branch
      run: git checkout -b Development upstream/Development


    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
          commit-message: 'Automated pull request'
          title: 'Automated pull request'
          branch: Development
          base: main # or any other branch you want to merge into
          token: ${{ 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 }}

    - name: Remove remote URL
      run: git remote remove original
