name: Create Pull Request

on:
  push:
    branches:
      - main

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2.4.2

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        branch: my-feature-branch
        title: My Pull Request Title
        body: |
          My pull request description.
          It can include multiple lines of text.

        commit-message: My commit message
        labels: |
          label1
          label2
