# Define the name of the job
name: Test

# Define the trigger for the job
on:
  push:
    branches: [ Development ]

# Define the steps for the job
jobs:
  test:
    # Define the operating system for the job
    runs-on: ubuntu-latest-16.04

    # Define the steps to run
    steps:
    - name: Checkout code
      uses: actions/checkout@v2.5.2
    - name: Install dependencies
      run: |
        npm install \
          vue3-charts --save \
          resize-observer-polyfill --save-dev
    - name: Run tests
      run: npm run test:unit

    # Define the step to push changes if the test passes
    - name: Push changes
      if: ${{ job.status == 'success' }}
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: CI build passed [skip ci]
