# Define the trigger for the job

name: CI

on:
 push:
    branches: [ Development ]


# Define the steps for the job
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2.4.2
    - name: Install dependencies
      run: |
        npm install \
          vue3-charts --save \
          resize-observer-polyfill --save-dev
    - name: Run tests
      run: npm run test:unit
      
  deploy:
    needs: build
    if: success()
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Push changes to GitHub
        uses: ad-m/github-push-action@master
        with:
          branch: development
          force: true
