# This is a YAML configuration file for a Node.js project

# Define the name of the job
name: Test

# Define the trigger for the job
on:
  push:
    branches: [ Development ]

# Define the jobs for the workflow
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        npm install \
          vue3-charts --save \
          resize-observer-polyfill --save-dev
    - name: Build
      run: npm run build
    - name: Deploy
      run: npm run deploy
      if: success()

  test:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ needs.build.result != 'failure' }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        npm install \
          vue3-charts --save \
          resize-observer-polyfill --save-dev
    - name: Run tests
      run: npm run test:unit
