name: Create Pull Request

on:
  push:
    branches:
      - main

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2.4.2

    - name: Set remote URL
      run: git remote add original https://github.com/ArthurBrouwersSemester3/Front-end.git

    - name: Fetch branch
      run: git fetch original Development

    - name: Checkout branch
      run: git checkout -b Development original/Development

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        branch: Development
        title: My Pull Request Title
        body: |
          My pull request description.
          It can include multiple lines of text.
        commit-message: My commit message
        labels: |
          label1
          label2 

    - name: Remove remote URL
      run: git remote remove original
